"""empty message

Revision ID: 39c66d85217e
Revises: None
Create Date: 2014-10-31 01:25:28.944099

"""

# revision identifiers, used by Alembic.
revision = '39c66d85217e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
